### ISSUE TITLE
Depends: python-pyqt5 but it is not installable

### ISSUE THREAD

**Issue by joellohyy** [sciapp/pyMolDyn#1]
Hi I've tried installing pymoldyn through your website https://pgi-jcns.fz-juelich.de/portal/pages/pymoldyn-main.html,  with the list of instructions using ubuntu, however when I sudo apt-get install pymoldyn it returns  
pymoldyn : Depends: python-pyqt5 but it is not installable
            Depends: python-pyqt5.qtopengl but it is not installable
            Depends: python-pyqt5.qtwebkit but it is not installable
E: Unable to correct problems, you have held broken packages.

I've installed PyQt5 in usr/bin/python3.4 and I've set the python default to that python version but it returns the same error. I'm not sure if the module it is looking for is pyqt5 or PyQt5.

**Comment by FlorianRhiem** [comment]
Hello,
what version of Ubuntu are you using? We test the installation on Ubuntu 16.04 and 17.04, which both offer the *python-pyqt5* package ([xenial/python-pyqt5](https://packages.ubuntu.com/xenial/python-pyqt5) and [zesty/python-pyqt5](https://packages.ubuntu.com/zesty/python-pyqt5)).
If you are using one of these versions, please try installing *python-pyqt5* by itself, independent of pymoldyn:
```sudo apt install python-pyqt5```

**Comment by joellohyy** [comment]
I'm on Ubuntu 14.04. 
I tried sudo apt-get install python-pyqt5 but it returns "Package python-pyqt5 is not available, but is referred to by another package."

**Comment by FlorianRhiem** [comment]
The packages we currently build for Ubuntu only work on 16.04 and 17.04, as Ubuntu 14.04 doesn't have the dependencies of pyMolDyn available (16.10 should work as well, but isn't supported by Canonical anymore, so I have updated the documentation accordingly).

In this case, please install pyMolDyn from [source](https://github.com/sciapp/pyMolDyn/archive/release-0.9.8.tar.gz).
